
import React, { useRef } from "react";
import { useReactToPrint } from "react-to-print";

const WalletExportPDF = ({ walletAddress, stats, aiInsight, chartComponent, txTableComponent }) => {
  const componentRef = useRef();

  const handlePrint = useReactToPrint({
    content: () => componentRef.current,
    documentTitle: "Wallet_Intelligence_Report_" + walletAddress.slice(0, 8),
  });

  return (
    <div className="my-6">
      <button
        onClick={handlePrint}
        className="bg-green-700 hover:bg-green-600 text-white px-4 py-2 rounded font-semibold"
      >
        📄 Export Full PDF Report
      </button>

      <div ref={componentRef} className="p-8 bg-white text-black rounded mt-4 max-w-5xl mx-auto shadow-md">
        <h1 className="text-2xl font-bold mb-4">🧠 Wallet Intelligence Report</h1>
        <p><strong>Wallet Address:</strong> {walletAddress}</p>

        <div className="mt-4">
          <h2 className="text-xl font-semibold mb-2">AI Behavioral Insight</h2>
          <p className="text-yellow-800 bg-yellow-100 border border-yellow-300 p-3 rounded">{aiInsight}</p>
        </div>

        <div className="mt-4">
          <h2 className="text-xl font-semibold mb-2">Statistical Overview</h2>
          <ul className="list-disc ml-6 space-y-1">
            <li>Total Transactions: {stats.totalTx}</li>
            <li>Total Volume: {stats.totalValueETH.toFixed(4)} ETH</li>
            <li>Average Transaction Value: {stats.averageValueETH.toFixed(4)} ETH</li>
            <li>Failed Transactions: {stats.failedTx}</li>
            <li>Self Transfers: {stats.selfTransfers}</li>
            <li>Contract Calls: {stats.contractsCalled}</li>
          </ul>
        </div>

        <div className="mt-6">
          <h2 className="text-xl font-semibold mb-2">📊 Transaction Volume Chart</h2>
          <div>{chartComponent}</div>
        </div>

        <div className="mt-6">
          <h2 className="text-xl font-semibold mb-2">📋 Filtered Transactions Table</h2>
          <div>{txTableComponent}</div>
        </div>

        <div className="mt-6 pt-6 text-sm text-gray-500 border-t">
          Generated by AEGIX System — {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
};

export default WalletExportPDF;
